name: in_app_scanner
description: "A Flutter widget for barcode scanning and image capturing using a single camera."
version: 1.0.3
repository: https://github.com/Mohiuddin655-PUB/flutter_in_app_scanner.git

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0+1
  google_mlkit_barcode_scanning: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter: